services:
  postgres:
    image: postgres:16
    container_name: tapline-postgres
    environment:
      POSTGRES_DB: [DATABASE_NAME]
      POSTGRES_USER: [USER_NAME]
      POSTGRES_PASSWORD: [USER_PASSWORD]
    ports:
      - "5432:5432"
    volumes:
      - tapline_pgdata:/var/lib/postgresql/data
volumes:
  tapline_pgdata:
