[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "VisioEval"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["VisioEval"]

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff]
line-length = 120
ignore = ["D100", "D101", "D102", "D103", "D107", "S101"]
